import { motion, AnimatePresence } from "framer-motion";
import { IoClose, IoSparkles } from "react-icons/io5";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import { CircularProgress } from "@mui/material";
import PropTypes from "prop-types";

const sampleAIResponse = `# AI Agent Analysis Report

## Executive Summary

Based on the analyzed data, here are the key insights and recommendations:

### Performance Metrics

- **Response Time**: 98.5% of queries processed within 2 seconds
- **Accuracy Rate**: 94.2% user satisfaction score
- **Daily Active Users**: 1,247 (+23% from last month)

### Top Categories

1. **Technical Support** - 342 requests
2. **Billing Inquiries** - 289 requests
3. **General Questions** - 198 requests

## Detailed Findings

### User Behavior Patterns

The AI agent has identified several patterns in user interactions:

\`\`\`javascript
const userPatterns = {
  peakHours: "14:00 - 18:00",
  averageSessionDuration: "4.5 minutes",
  returnRate: "67%"
};
\`\`\`

### Recommendations

> **Note**: These recommendations are generated based on real-time data analysis.

- ✅ Increase support capacity during peak hours
- ✅ Implement proactive notifications for common issues
- ✅ Enhance self-service options for billing inquiries

### Code Example

Here's a sample implementation for optimizing response times:

\`\`\`python
class AIOptimizer:
    def __init__(self, config):
        self.config = config
        self.cache = {}
    
    def optimize_response(self, query):
        if query in self.cache:
            return self.cache[query]
        
        response = self.process_query(query)
        self.cache[query] = response
        return response
\`\`\`

## Next Steps

| Priority | Action Item | Timeline |
|----------|-------------|----------|
| High | Deploy caching system | 1 week |
| Medium | Update training data | 2 weeks |
| Low | UI enhancements | 3 weeks |

---

*Generated by AI Agent v2.0 on ${new Date().toLocaleDateString('ru-RU')}*
`;

export default function AIResponseModal({ isOpen, onClose, content, isLoading }) {
    return (
        <AnimatePresence>
            {isOpen && (
                <>
                    {/* Backdrop */}
                    <motion.div
                        initial={{ opacity: 0 }}
                        animate={{ opacity: 1 }}
                        exit={{ opacity: 0 }}
                        transition={{ duration: 0.2 }}
                        className="fixed inset-0 bg-black/50 backdrop-blur-sm z-40"
                        onClick={onClose}
                    />

                    {/* Modal */}
                    <div className="fixed inset-0 flex items-center justify-center z-50 p-4 pointer-events-none">
                        <motion.div
                            initial={{ opacity: 0, scale: 0.95, y: 20 }}
                            animate={{ opacity: 1, scale: 1, y: 0 }}
                            exit={{ opacity: 0, scale: 0.95, y: 20 }}
                            transition={{
                                type: "spring",
                                duration: 0.5,
                                bounce: 0.3
                            }}
                            className="bg-white rounded-2xl shadow-2xl max-w-4xl w-full max-h-[85vh] flex flex-col pointer-events-auto overflow-hidden border border-gray-100"
                        >
                            {/* Header */}
                            <div className="flex items-center justify-between px-6 py-4 border-b border-gray-100 bg-gradient-to-r from-purple-50 to-violet-50">
                                <div className="flex items-center gap-3">
                                    <div className="w-10 h-10 rounded-xl bg-gradient-to-br from-purple-600 to-violet-600 flex items-center justify-center shadow-lg">
                                        <IoSparkles className="text-white text-xl" />
                                    </div>
                                    <div>
                                        <h2 className="text-xl font-bold text-gray-800">AI Agent Response</h2>
                                        <p className="text-xs text-gray-500">Автоматически сгенерировано</p>
                                    </div>
                                </div>
                                <motion.button
                                    whileHover={{ scale: 1.05, rotate: 90 }}
                                    whileTap={{ scale: 0.95 }}
                                    onClick={onClose}
                                    className="w-9 h-9 rounded-lg bg-white hover:bg-gray-100 flex items-center justify-center transition-colors shadow-sm border border-gray-200"
                                    aria-label="Close modal"
                                >
                                    <IoClose className="text-gray-600 text-xl" />
                                </motion.button>
                            </div>

                            {/* Content */}
                            <div className="flex-1 overflow-y-auto px-6 py-6">
                                {isLoading ? (
                                    <div className="flex flex-col items-center justify-center h-64 gap-4">
                                        <CircularProgress size={48} thickness={4} sx={{ color: '#7c3aed' }} />
                                        <p className="text-gray-500 text-sm">Получение ответа от AI агента...</p>
                                    </div>
                                ) : (
                                    <div className="prose prose-sm max-w-none prose-headings:text-gray-800 prose-p:text-gray-600 prose-strong:text-gray-800 prose-code:text-purple-600 prose-code:bg-purple-50 prose-code:px-1.5 prose-code:py-0.5 prose-code:rounded prose-pre:bg-gray-900 prose-pre:text-gray-100 prose-a:text-purple-600 prose-a:no-underline hover:prose-a:underline prose-blockquote:border-purple-500 prose-blockquote:bg-purple-50 prose-blockquote:py-1 prose-table:text-sm">
                                        <ReactMarkdown remarkPlugins={[remarkGfm]}>
                                            {content || sampleAIResponse}
                                        </ReactMarkdown>
                                    </div>
                                )}
                            </div>

                            {/* Footer */}
                            <div className="px-6 py-4 border-t border-gray-100 bg-gray-50 flex justify-end">
                                <motion.button
                                    whileHover={{ scale: 1.02 }}
                                    whileTap={{ scale: 0.98 }}
                                    onClick={onClose}
                                    className="px-6 py-2.5 bg-gradient-to-r from-purple-600 to-violet-600 text-white rounded-xl font-medium shadow-lg shadow-purple-500/30 hover:shadow-xl hover:shadow-purple-500/40 transition-all"
                                >
                                    Закрыть
                                </motion.button>
                            </div>
                        </motion.div>
                    </div>
                </>
            )}
        </AnimatePresence>
    );
}

AIResponseModal.propTypes = {
    isOpen: PropTypes.bool.isRequired,
    onClose: PropTypes.func.isRequired,
    content: PropTypes.string,
    isLoading: PropTypes.bool,
};
